sonar.projectKey=auto-sub-clone
sonar.projectName=auto-sub-clone
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,coverage/**
